### PR TITLE
Use artifact caching proxy for `backend-extension-indexer`

### PR DESCRIPTION
**Pull request by lemeurherve**
Ref: https://github.com/jenkins-infra/helpdesk/issues/2752

### CODE REVIEW

**Comment by lemeurherve** [comment]
> Since the last commit there are downloads from `central` and some `Blocked mirror for repositories: [maven.jenkins-ci.org (http://repo.jenkins-ci.org/public/, default, releases+snapshots)]` errors which I can't yet explain. 🤔 I need to take a deeper look, putting this PR in draft.

Nothing like that in the last build `#7`, PR ready to review.

**Comment by lemeurherve** [comment]
About the first occurrence of "Blocked mirror" error, I've noticed the presence of a `<profile>` section in the corresponding plugin: https://github.com/jenkinsci/audit2db-plugin/blob/458af2ac90ef8dde006e0f23911038463336782a/pom.xml#L413-L435

Is this section mandatory? Can it be removed?

**Comment by MarkEWaite** [comment]
> About the first occurrence of "Blocked mirror" error, I've noticed the presence of a `<profile>` section in the corresponding plugin: https://github.com/jenkinsci/audit2db-plugin/blob/458af2ac90ef8dde006e0f23911038463336782a/pom.xml#L413-L435
> 
> Is this section mandatory? Can it be removed?

I believe it is mandatory because it is choosing the test database driver based on test execution context.  When not in the `jenkins-ci` context, a different driver would be used and the `jenkins-ci` profile would be deactivated from the maven command line.

**Comment by lemeurherve** [comment]
The issue was that the artifact caching proxy wasn't correctly configured on infra.ci.jenkins.io and lagged behind the ones on ci.jenkins.io, noticed and fixed that today in https://github.com/jenkins-infra/kubernetes-management/pull/3651

PR ready for review

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
